Repository FE-J5/fandom-k, pull requests merged in 2024-09, with the labels that each got.

#34 Feat(#32): DonationAwait 제작
  package-lock.json
  package.json
  src/assets/img/cover_donation.svg
  src/components/ArrowButton.jsx
  src/components/BoxButton.jsx
  src/components/DonationAwait/CardProfile.jsx
  src/components/DonationAwait/DonationAwait.jsx
  src/pages/List.jsx
Labels: feature

#35 feat(29): Credit 박스 제작
  src/assets/icon/credit_icon.svg
  src/components/Credit.jsx
  src/components/MonthChart/Chart.jsx
  src/pages/List.jsx
Labels: feature

#37 feat(31): VoteModal 제작
  public/index.html
  src/components/Header.jsx
  src/components/Modal/VoteModal.jsx
  src/components/MonthChart/MonthChart.jsx
  src/components/RadioButton/RadioButton.jsx
  src/styles/global.jsx
Labels: feature

#42 refactor(38): MonthChart 윗 margin 수정, votesImageChart API 수정
  package-lock.json
  src/api/votesImageChart.js
  src/components/MonthChart/MonthChart.jsx
Labels: refactor

#48 Refactor(19) : Mypage localStorage 및 반응형 디자인 구현
  src/components/Mypage/CommonStyle.jsx
  src/components/Mypage/FavoriteIdolList.jsx
  src/components/Mypage/IdolList.jsx
  src/hooks/useIdols.jsx
  src/hooks/usePageSize.jsx
  src/pages/MyPage.jsx
Labels: feature, refactor
